[tox]
minversion = 3.28.0
envlist = py39
skipsdist = true

[testenv]
basepython = python3.9
passenv = *
deps =
    -r tox-requirements.txt
    ansible-core==2.15.13
commands =
    {posargs:molecule test -s compatibility --destroy always}
